name: Netflix Clone CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: |
          docker build -t myrepo/netflix-backend:latest ./backend
          docker build -t myrepo/netflix-frontend:latest ./frontend

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myrepo/netflix-backend:latest
          docker push myrepo/netflix-frontend:latest
